name: jupyterlab-code-formatter
channels:
  - conda-forge
  - r
dependencies:
  - jupyterlab==2.0.0
  - rpy2
  - r-formatr
  - r-styler
  - nodejs
  - jq
  - gawk
  - inotify-tools
  - pip
  - pip:
    - autopep8
    - black
    - isort
    - pytest
    - sphinx
    - sphinx_rtd_theme
    - twine
    - yapf
