name: jupyterlab-code-formatter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _r-mutex=1.0.1=anacondar_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_17
  - bleach=3.1.1=py_0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py38_0
  - cffi=1.14.0=py38hd463f26_0
  - curl=7.68.0=hf8cf82a_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_1000
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gawk=5.0.1=h516909a_1
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_17
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_17
  - glib=2.58.3=py38h6f030ca_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gsl=2.6=h294904e_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_17
  - harfbuzz=2.4.0=h9f30f68_3
  - icu=64.2=he1b5a44_1
  - importlib_metadata=1.5.0=py38_0
  - inotify-tools=3.20.2=h516909a_0
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9c=h14c3975_1001
  - jq=1.6=h14c3975_1000
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.0.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=2.0.0=py_1
  - jupyterlab_server=1.0.7=py_0
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_openblas
  - libopenblas=0.3.8=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.3=h516909a_0
  - markupsafe=1.1.1=py38h516909a_0
  - mistune=0.8.4=py38h516909a_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - nodejs=13.9.0=h10a4023_0
  - notebook=6.0.3=py38_0
  - oniguruma=6.9.3=h516909a_0
  - openssl=1.1.1d=h516909a_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.6.2=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pygments=2.5.2=py_0
  - pyrsistent=0.15.7=py38h516909a_0
  - python=3.8.2=h9d8adfe_4_cpython
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=19.0.0=py38h1768529_0
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.5=r36hcdcec82_0
  - r-base=3.6.2=h7ed4ef7_1
  - r-cli=2.0.2=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-digest=0.6.25=r36h0357c0b_0
  - r-ellipsis=0.3.0=r36hcdcec82_0
  - r-fansi=0.4.1=r36hcdcec82_0
  - r-formatr=1.7=r36h6115d3f_1
  - r-glue=1.3.1=r36hcdcec82_1
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-pillar=1.4.3=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_0
  - r-purrr=0.3.3=r36hcdcec82_0
  - r-r.cache=0.14.0=r36h6115d3f_0
  - r-r.methodss3=1.8.0=r36h6115d3f_0
  - r-r.oo=1.23.0=r36h6115d3f_0
  - r-r.utils=2.9.2=r36h6115d3f_0
  - r-rematch2=2.1.0=r36h6115d3f_0
  - r-rlang=0.4.5=r36hcdcec82_0
  - r-rprojroot=1.3_2=r36h6115d3f_1002
  - r-styler=1.3.2=r36h6115d3f_0
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-vctrs=0.2.3=r36hcdcec82_0
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-xfun=0.12=r36h6115d3f_0
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - readline=8.0=hf8c457e_0
  - rpy2=3.1.0=py38r36hc1659b7_3
  - sed=4.7=h1bed415_1000
  - send2trash=1.5.0=py_0
  - setuptools=45.2.0=py38_0
  - simplegeneric=0.8.1=py_1
  - six=1.14.0=py38_0
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - tornado=6.0.4=py38h516909a_0
  - traitlets=4.3.3=py38_0
  - tzlocal=2.0.0=py_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.3
    - autopep8==1.5
    - babel==2.8.0
    - black==19.10b0
    - chardet==3.0.4
    - click==7.0
    - cryptography==2.8
    - docutils==0.16
    - idna==2.9
    - imagesize==1.2.0
    - isort==4.3.21
    - jeepney==0.4.3
    - keyring==21.1.1
    - more-itertools==8.2.0
    - packaging==20.3
    - pathspec==0.7.0
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - py==1.8.1
    - pycodestyle==2.5.0
    - pyparsing==2.4.6
    - pytest==5.3.5
    - readme-renderer==24.0
    - regex==2020.2.20
    - requests==2.23.0
    - requests-toolbelt==0.9.1
    - secretstorage==3.1.2
    - snowballstemmer==2.0.0
    - sphinx==2.4.4
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - toml==0.10.0
    - tqdm==4.43.0
    - twine==3.1.1
    - typed-ast==1.4.1
    - urllib3==1.25.8
    - yapf==0.29.0

