name: jupyterlab_code_formatter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - anyio=2.0.2=py39hf3d152e_2
  - argon2-cffi=20.1.0=py39hbd71b63_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py39h38d8fee_1001
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py39hf3d152e_0
  - cffi=1.14.4=py39h261ae71_0
  - chardet=4.0.0=py39hf3d152e_0
  - cryptography=3.3.1=py39h3c74f83_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.3.0=py39hf3d152e_2
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - ipykernel=5.4.2=py39hef51801_0
  - ipython=7.19.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py39hf3d152e_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py39hf3d152e_0
  - jupyter_server=1.1.3=py39hf3d152e_0
  - jupyterlab=3.0.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.0.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuv=1.40.0=hd18ef5c_0
  - markupsafe=1.1.1=py39h38d8fee_2
  - mistune=0.8.4=py39hbd71b63_1002
  - nbclassic=0.2.5=pyhd8ed1ab_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py39hf3d152e_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nodejs=15.3.0=h25f6087_0
  - notebook=6.1.6=py39hf3d152e_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - pandoc=2.11.3.1=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.3.3=py39h06a4308_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.3=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39hbd71b63_1
  - pysocks=1.7.1=py39h079e4ff_2
  - python=3.9.1=hdb3f193_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2020.5=pyhd8ed1ab_0
  - pyzmq=20.0.0=py39h25affbc_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=51.0.0=py39h06a4308_2
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py39hf3d152e_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.1=py39hf3d152e_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39hbd71b63_0
  - traitlets=5.0.5=py_0
  - tzdata=2020d=h14c3975_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - black==20.8b1
    - click==7.1.2
    - iniconfig==1.1.1
    - isort==5.6.4
    - mypy-extensions==0.4.3
    - pathspec==0.8.1
    - pluggy==0.13.1
    - py==1.10.0
    - pytest==6.2.1
    - regex==2020.11.13
    - toml==0.10.2
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3

