# a mybinder.org-ready environment for demoing jupyterlab_code_formatter
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-code-formatter-demo
#
name: jupyterlab-code-formatter-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
